### ISSUE TITLE
Base template

### ISSUE THREAD

**Issue by iviaks** [iviaks/front-edu#4]
## Задание
Нужно сделать базовую страницу с такими элементами:
-  header (высота: 50px);
-  левое меню (высота: 200px);
-  content (высота: 400px);
-  footer (высота: 50px).

## Примечание
Блоки для наглядности сделать разного цвета

Не нужно забывать про сброс стилей:
```css
html, body {
  margin: 0;
  padding: 0;
}
```

## Результат
Результат должен быть в файле **index.html**.
![result](http://dl3.joxi.net/drive/2017/08/14/0020/2358/1321270/70/0c1017b7b2.png)
[Решение смотреть только в крайнем случае](https://codepen.io/anon/pen/rzGzEJ)

**Comment by Anya2ka** [comment]
This close #4.
